### PR TITLE
Less code

### PR DESCRIPTION
**Pull request by cktang88**

### CODE REVIEW

**Comment by yunyu** [comment]
Lesser code:

    altered += i % 2 ? text[i].toUpperCase() : text[i].toLowerCase();

**Comment by yunyu** [comment]
Lesser code:

```js
export default function spongebobify(text) {
    return Array.from(text).reduce((acc, el, i) => acc += i % 2 ? el.toUpperCase() : el.toLowerCase(), '');
}
```

**Comment by bencooper222** [comment]
I'm going to setup CI before accepting this PR 😉

**Comment by bencooper222** [comment]
image

This will be the best maintained needless JavaScript library ever.

**Comment by bencooper222** [comment]
@cktang88 pull my updates (b28f7cd76252e995b5c62cffee40319054bf87dd) with the units tests + travis file and the CI should work.

**Comment by bencooper222** [comment]
Code is already shorter.

**Pull request closed without merging**
